### PR TITLE
Feat: Navigation Added

### PR DESCRIPTION
**Pull request by Sen-442b**
**Features:-**
- Navigation bar with 3 item categories
- Fluid Height 

**Limitations**
- Unresponsive 

**Upcoming Features**
- Menu bars on mobile screens

### CODE REVIEW

**Comment by Sen-442b** [comment]
image

**Review by manojkumar8400 — APPROVED** [review]
looks good to me.

**Review by sakshamAK — APPROVED** [review]
Looks good to me

**Comment by preethasri** [comment]
Looks neat 👍

**Pull request merged**
